ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
]

story7/urls.py
from django.urls import path
from .views import *

app_name = 'story7'

urlpatterns = [
    path('', statuses, name='statuses'),
    path('confirmation', confirmation, name='confirmation'),
]

story8/urls.py
from django.urls import path
from .views import *

app_name = 'story8'

urlpatterns = [
    path('accordion', accordion, name='accordion'),
]

story7/models.py
from django.db import models

# Create your models here.
class S7(models.Model):
    name = models.CharField('Nama', max_length=50)
    status = models.TextField('Status')

story8/models.py
from django.db import models

# Create your models here.

story7/forms.py
from django.forms import ModelForm
from .models import S7

class StatusForm(ModelForm):
    class Meta:
        model = S7
        fields = ['name', 'status']

story7/views.py
from django.shortcuts import render
from .models import S7
from .forms import StatusForm

# Create your views here.
def statuses(request):
    if request.method == 'POST':
        name = request.POST['name']
        status = request.POST['status']
        S7.objects.create(name = name, status = status)
    return render(request, 'story7.html', 
        {'statlist': S7.objects.all(), 'form': StatusForm()})

def confirmation(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        return render(request, 'confirmation.html',
        {'name': form.data['name'], 'status': form.data['status']})

story8/views.py
from django.shortcuts import render

# Create your views here.
def accordion(request):
    return render(request, 'accordion.html')

story7/templates/confirmation.html
{% extends 'includes/base.html' %}
{% load static %}
{% block title %} Konfirmasi {% endblock %}

{% block content %}
    <div class="container-fluid padding confirmation">
        <h1>Tambahkan status?</h1>
        <p>{{ name }}</p>
        <h5>{{ status }}</h5>
        <form action="/" method="POST">
            {% csrf_token %}
            <input type="hidden" name="name" value="{{ name }}">
            <input type="hidden" name="status" value="{{ status }}">
            <input type="submit" id="confirm" value="Ya">
        </form>
    
        <div class="down">
            <form action="/" method="GET">
                <input type="submit" id="cancel" value="Batalkan">
            </form>
        </div>   
    </div>
{% endblock %}

story7/templates/includes/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        {% block title %} {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    </head>

<body>
    {% include 'includes/navbar.html' %}
    {% block content %} {% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    {% block script %} {% endblock %}
</body>

</html>

story7/templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-light">
    <a class="navbar-brand" href="{% url 'story7:statuses' %}">PPW Story</a>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'story8:accordion' %}">Accordion</a>
        </li>
    </ul>
</nav>

story7/templates/story7.html
{% extends 'includes/base.html' %}
{% load static %}
{% block title %} Status Board {% endblock %}

{% block content %}
    <div class="container-fluid padding">
        <div class="row">
            {% for i in statlist %}
                <div class="col-sm-6 status">
                    <p>{{i.name}}</p>
                    <h5>{{i.status}}</h5>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="container-fluid footer">
        <form action="confirmation" method="POST" validate>
            {% csrf_token %}
            <table class="table mx-5" style="width:90vw">
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td><input id="submit" type="submit" value="Submit" class="btn btn-primary click"></td>
            </tr>
            </table>
        </form>
    </div>
{% endblock %}

story8/templates/accordion.html
{% extends 'includes/base.html' %}
{% load static %}
{% block title %} Accordion {% endblock %}

{% block content %}
    <center>
        <div class="container-fluid padding accordion">
            <div id="profile" class="accord">
                <div class="container accordiontitle">
                    <h4 class="nomargin">Profil Saya</h4>
                    <button class="moveup">^</button>
                    <button class="movedown">v</button>
                </div>
                <div class="container accordioncontent">
                    <p class="accordionlines">Syabib Ash-Shiddiqi</p>
                    <p class="accordionlines">19 tahun</p>
                    <p class="accordionlines">Ilmu Komputer Universitas Indonesia</p>
                </div>
            </div>
            <div id="activity" class="accord">
                <div class="container accordiontitle">
                    <h4 class="nomargin">Aktivitas</h4>
                    <button class="moveup" id="moveuptest">^</button>
                    <button class="movedown">v</button>
                </div>
                <div class="container accordioncontent">
                    <p class="accordionlines">Ngoding</p>
                    <p class="accordionlines">Proyekan</p>
                    <p class="accordionlines">Kepanitiaan</p>
                    <p class="accordionlines">Trying to survive through PPW</p>
                </div>
            </div>
            <div id="experience" class="accord">
                <div class="container accordiontitle">
                    <h4 class="nomargin" id="accordtest">Pengalaman</h4>
                    <button class="moveup">^</button>
                    <button class="movedown" id="movedowntest">v</button>
                </div>
                <div class="container accordioncontent">
                    <p class="accordionlines">PO SIWAK 2020</p>
                    <p class="accordionlines">Taring Maung</p>
                    <p class="accordionlines">DPH Rohis SMAN 1 Padang</p>
                </div>
            </div>
            <div id="achievements" class="accord">
                <div class="container accordiontitle">
                    <h4 class="nomargin">Prestasi</h4>
                    <button class="moveup">^</button>
                    <button class="movedown">v</button>
                </div>
                <div class="container accordioncontent">
                    <p class="accordionlines">Pengen flexing tapi yang nyodok PPW OP semua jadi minder</p>
                </div>
            </div>
        </div>

        <p class="watermark">IF I COULD LIVE THROUGH THIS SEMESTER I COULD DO ANYTHING</p>
    </center>
{% endblock %}

story8/templates/includes/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        {% block title %} {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    </head>

<body>
    {% include 'includes/navbar.html' %}
    {% block content %} {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.0.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/accordion.js' %}"></script>
    {% block script %} {% endblock %}
</body>

</html>

story8/templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-light">
    <a class="navbar-brand" href="{% url 'story7:statuses' %}">PPW Story</a>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'story8:accordion' %}">Accordion</a>
        </li>
    </ul>
</nav>